language: android

jdk:
 - oraclejdk7

script: ./gradlew build -x signArchives

android:
  components:
    - build-tools-20.0.0
    - android-19
    - addon-google_gdk-google-19

notifications:
  email: false
